import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./layout/Navbar";
import { Quicksand, Poppins } from "next/font/google";

const quicksand = Quicksand({
  weight: "300",
  subsets: ["latin"],
});
const poppins = Poppins({
  weight: "300",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.className}`}>
      <body className="">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
